#pragma config(Sensor, S4,     ,               sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "libs/smux utils.h"
#include "libs/display.h"

task main()
{

	while(true)
	{

	}
}
